name: pingidsdk
description: Flutter plugin to support PingID SDK Integration. Currently implemented all events and mostly methods of the SDK v1.11. 
version: 0.0.3
homepage: https://github.com/sandrocaseiro/pingidsdk-flutter
repository: https://github.com/sandrocaseiro/pingidsdk-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sandrocaseiro.pingidsdk
        pluginClass: PingidsdkPlugin
      # ios:
      #   pluginClass: PingidsdkPlugin
